#!/bin/bash
# Generate the per-student files of the HTTP lab from the seed values.
#
#   scripts/personalise.sh <student-id>
#
# Writes (both git-ignored, both bind-mounted into the containers):
#   configs/generated/student.conf   nginx `map` variables used by the web
#                                    server and the HTTPS server configs
#   content/generated/index.html     the start page with a hidden note whose
#                                    length depends on the student
#
# Called by bootstrap.sh before every deploy; safe to re-run.
set -euo pipefail

LAB_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ID=${1:?usage: $0 <student-id>}

eval "$("$LAB_DIR/scripts/student-seed.sh" "$ID")"

mkdir -p "$LAB_DIR/configs/generated" "$LAB_DIR/content/generated"

# ---- nginx variables ------------------------------------------------------
items=""
i=1
for name in $ITEM_NAMES; do
    items="${items:+$items, }{\"id\": $i, \"name\": \"$name\"}"
    i=$(( i + 1 ))
done

cat > "$LAB_DIR/configs/generated/student.conf" <<EOF
# Generated by scripts/personalise.sh for student $STUDENT_ID - do not edit.
map \$host \$s_token           { default "$TOKEN"; }
map \$host \$s_index_maxage    { default "$INDEX_MAXAGE"; }
map \$host \$s_private_maxage  { default "$PRIVATE_MAXAGE"; }
map \$host \$s_items           { default '{"items": [$items]}'; }
map \$host \$s_created         { default '{"status": "created", "id": $NEXT_ID, "message": "Item created successfully"}'; }
map \$host \$s_items_allow     { default "GET, POST"; }
map \$host \$s_hsts_maxage     { default "$HSTS_MAXAGE"; }
EOF

# ---- start page with a student-specific hidden note ----------------------
NOTES=(
"HTTP is a stateless request-response protocol."
"Every response starts with a status line."
"Headers are case-insensitive, their values are not."
"A HEAD request returns headers without a body."
"Caches may store responses marked public."
"Private responses are for a single user only."
"An ETag identifies one version of a resource."
"If-None-Match lets a client validate its copy."
"A 304 response carries no body."
"max-age counts seconds from the origin's Date."
"Age tells how long a copy sat in a cache."
"stale-while-revalidate allows a short grace period."
"no-store means never write this response to disk."
"no-cache means revalidate before every reuse."
"Vary lists the request headers a cache must key on."
"Compression is negotiated with Accept-Encoding."
"Content-Length is unknown when the body is chunked."
"Keep-alive reuses one TCP connection for many requests."
"HTTPS wraps HTTP in a TLS session."
"SNI sends the server name in clear text."
"HSTS tells browsers to use HTTPS from now on."
"A 301 redirect is remembered by the browser."
"The Server header names the server software."
"User-Agent identifies the client software."
)
{
    echo "<!-- lab notes ($TOKEN)"
    for (( n = 0; n < INDEX_NOTE_LINES; n++ )); do
        echo "     ${NOTES[$(( n % ${#NOTES[@]} ))]}"
    done
    echo "-->"
} > "$LAB_DIR/content/generated/.note.html"

# insert the note just before </body>
awk -v notefile="$LAB_DIR/content/generated/.note.html" '
    /<\/body>/ { while ((getline line < notefile) > 0) print line; close(notefile) }
    { print }
' "$LAB_DIR/content/www/index.html" > "$LAB_DIR/content/generated/index.html"
rm -f "$LAB_DIR/content/generated/.note.html"

echo "$TOKEN"
